<?php
    get_header();
    get_template_part("/partials/front-page/banner");
    get_template_part("/partials/front-page/middle1");
    get_template_part("/partials/front-page/middle2");
    get_template_part("/partials/front-page/bottom1");
    get_template_part("/partials/sermons/section1");
    get_template_part("/partials/front-page/bottom3");
    get_template_part("/partials/front-page/bottom4");
    get_footer();
?>