<?php
    get_header();
    get_template_part("/components/banner");
    get_template_part("/components/middle1");
    get_template_part("/components/middle2");
    get_template_part("/components/bottom1");
    get_template_part("/components/bottom2");
    get_footer();
?>